version: "3"
volumes:
  mysql_data:
  vendor_bundle:
  node_modules:
  public_spree:
  storage:

services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - default
    ports:
      - '33306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
  potepanec:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
    depends_on:
      - mysql
    networks:
      - default
    volumes:
      - .:/potepanec
      # https://qiita.com/shotat/items/57d049793605ffc20135
      - /potepanec/log
      - /potepanec/tmp
      - vendor_bundle:/potepanec/vendor/bundle
      - node_modules:/potepanec/node_modules
      - public_spree:/potepanec/public/spree
      - storage:/potepanec/storage
    tty: true
    stdin_open: true
    command: bundle exec rails server -b 0.0.0.0
